name: Release Plugins
on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  node-tests:
    name: Build & Release Plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 2

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: '.nvmrc'

      - name: Run build
        env:
          NUXT_UI_PRO_LICENSE: "${{ secrets.NUXT_UI_PRO_LICENSE }}"
        run: make build-all

      - name: Release artifacts
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3
        if: github.ref_type == 'tag'
        with:
          files: '*.zip'
